# Generated by Django 6.1.1 on 2026-09-10 08:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('organizations', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='TwilioAccount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('twilio_account_sid', models.CharField(max_length=64)),
                ('auth_token_encrypted', models.BinaryField()),
                ('api_key_sid', models.CharField(blank=True, max_length=64)),
                ('api_key_secret_encrypted', models.BinaryField(blank=True, null=True)),
                ('status', models.CharField(default='connected', max_length=20)),
                ('connected_at', models.DateTimeField(auto_now_add=True)),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)ss', to='organizations.organization')),
            ],
            options={
                'unique_together': {('organization', 'twilio_account_sid')},
            },
        ),
        migrations.CreateModel(
            name='PhoneNumber',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone_number', models.CharField(max_length=20)),
                ('twilio_sid', models.CharField(max_length=64)),
                ('friendly_name', models.CharField(blank=True, max_length=255)),
                ('voice_webhook_configured', models.BooleanField(default=False)),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)ss', to='organizations.organization')),
                ('twilio_account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='phone_numbers', to='telephony.twilioaccount')),
            ],
            options={
                'unique_together': {('organization', 'phone_number')},
            },
        ),
    ]
