# Generated by Django 6.1.1 on 2026-09-10 19:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('telephony', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='twilioaccount',
            options={'ordering': ['-connected_at']},
        ),
    ]
