# Generated by Django 6.1.1 on 2026-09-10 10:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('agents', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='agent',
            options={'ordering': ['-created_at']},
        ),
    ]
